http:
 host: "0.0.0.0"
 port: "8081"
 path: "/api/*"
 
db:
 url: "jdbc:postgresql://155.133.26.236:5432/Human_Resource_Management"
 driver: "org.postgresql.Driver"
 
until:
  retries: "1"
  millisecs: "60000"
 

 
 
  
 